name: Deploy to EC2 Instance

on:
  push:
  workflow_dispatch:

env:
    EEC2_IP: "ec2-18-118-218-204.us-east-2.compute.amazonaws.com"
    GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: get env
        run: env | sort
      - name: Create ssh key
        run: |
          touch api_key.pem
          echo "${{ secrets.SSH_KEY }}" > api_key.pem
          chmod 400 api_key.pem
      - name: SSH and deploy
        run: |
            ssh -i api_key.pem ec2-user@${{ env.EEC2_IP }}
                "git pull https://${{ github.repository_owner }}:${{ env.GH_PAT_TOKEN }}@github.com/${{ github.repository }}.git
                docker-compose down
                docker-compose up -d --build
                sleep 5
                docker exec drf-wine-api-api-1 python /src/manage.py makemigrations
                docker exec drf-wine-api-api-1 python /src/manage.py migrate"
