name: Deploy to EC2 Instance

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "select deploy environment"
        type: choice
        default: 'test'
        options:
          - test
          - prod
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Deploy to my EC2 Dev instance
        if: ${{ inputs.environment }} == "test"
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: -avzr --delete
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.DEV_INSTANCE }}
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/${{ env.REPOSITORY_NAME }}"
          SCRIPT_AFTER: |
            cd ~/${{ env.REPOSITORY_NAME }}
            docker-compose down -v
            docker-compose up -d --build
            sleep 5
            docker exec wine-api-api-1 python3 /src/manage.py makemigrations
            docker exec wine-api-api-1 python3 /src/manage.py migrate

      - name: Deploy to my EC2 Prod instance
        if: ${{ inputs.environment }} == "prod"
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PROD_EC2_SSH_KEY }}
          ARGS: -avzr --delete
          SOURCE: "./"
          REMOTE_HOST: ${{ vars.PROD_INSTANCE }}
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/${{ env.REPOSITORY_NAME }}"
          SCRIPT_AFTER: |
            cd ~/${{ env.REPOSITORY_NAME }}
            DO DIFFERENT THINGS PROBABLY
