name: Deploy to EC2 Instance

on:
  push:
  workflow_dispatch:

env:
    EEC2_IP: "ec2-18-118-218-204.us-east-2.compute.amazonaws.com"
    OWNER: ${{ github.repository_owner }}
    REPO_NAME: ${{ github.event.repository.name }}
    GH_PAT_TOKEN: ${{ secrets.GH_PAT_TOKEN }}

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: get env
        run: env | sort
      - name: Create ssh key
        run: |
          touch api_key.pem
          echo "${{ secrets.SSH_KEY }}" > scripts/api_key.pem
          chmod 400 api_key.pem
      - name: Run deploy script
        run: scripts/deploy
#      - name: Verify instance running
#        run: curl http://89.207.132.170
