name: Deploy to EC2 Instance

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Run deploy script
        run: scripts/deploy
#      - name: Verify instance running
#        run: curl http://89.207.132.170
