name: Deploy to EC2 Instance

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "select deploy environment"
        type: choice
        default: 'test'
        options:
          - test
          - prod
      
jobs:
  deploy-test:
    runs-on: ubuntu-latest
    if: ${{ inputs.environment }} == "test"
    steps:
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v5.0.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-34-213-48-149.us-west-2.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/SampleExpressApp"
      - name: get env
        run: env | sort
      - name: Git Pull
        run: |
          cd ~/wine-api
          git pull https://${{ github.repository_owner }}:${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Restart Docker
        run: |
          cd ~/wine-api
          docker-compose down -v
          docker-compose up -d --build
          sleep 5
          docker exec wine-api-api-1 python3 /src/manage.py makemigrations
          docker exec wine-api-api-1 python3 /src/manage.py migrate
      - name: Job Complete Message
        run: |
          echo "Successfully deployed to UAT"
  # deploy-prod:

