name: Deploy to EC2 Instance

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: "select deploy environment"
        type: choice
        default: 'test'
        options:
          - test
          - prod
      
jobs:
  deploy-test:
    runs-on: [test]
    if: ${{ inputs.environment }} == "test"
    steps:
      - name: Git Pull
        run: |
          cd ${{ github.repository }}
          git pull https://${{ github.repository_owner }}:${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Restart Docker
        run: |
          cd ${{ github.repository }}
          docker compose down -v
          docker compose up -d --build
          python manage.py makemigrations
          python manage.py migrate
          sleep 5
          docker exec drf-wine-api-api-1 python /src/manage.py makemigrations
          docker exec drf-wine-api-api-1 python /src/manage.py migrate
  # deploy-prod:
